server:
  port: 8097
  max-http-header-size: 65546
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    # 密码 没有则可以不填
    password: 740616
    # 如果使用的jedis 则将lettuce改成jedis即可
    lettuce:
      pool:
        # 最大活跃链接数 默认8
        max-active: 8
        # 最大空闲连接数 默认8
        max-idle: 8
        # 最小空闲连接数 默认0
        min-idle: 0
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: 740616
      url: jdbc:mysql://127.0.0.1:3306/springboot
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat,wall


